<?php

namespace Milestone\Appframe\Seeder;

use Illuminate\Database\Seeder;

class ResourceFormFieldTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $_ = \DB::statement('SELECT @@GLOBAL.foreign_key_checks');
        \DB::statement('set foreign_key_checks = 0');
        \Milestone\Appframe\Model\ResourceFormField::truncate()
            ->create([	'resource_form' => '1', 	'name' => 'name', 	'type' => 'text', 	'label' => 'Name', 												])
            ->create([	'resource_form' => '1', 	'name' => 'email', 	'type' => 'text', 	'label' => 'Email', 												])
            ->create([	'resource_form' => '1', 	'name' => 'group', 	'type' => 'select', 	'label' => 'Group', 												])
            ->create([	'resource_form' => '2', 	'name' => 'name', 	'type' => 'text', 	'label' => 'Name', 												])
            ->create([	'resource_form' => '2', 	'name' => 'email', 	'type' => 'text', 	'label' => 'Email', 												])
            ->create([	'resource_form' => '3', 	'name' => 'name', 	'type' => 'text', 	'label' => 'Name', 												])
            ->create([	'resource_form' => '3', 	'name' => 'email', 	'type' => 'text', 	'label' => 'Email', 												])
            ->create([	'resource_form' => '4', 	'name' => 'name', 	'type' => 'text', 	'label' => 'Group Name', 												])
            ->create([	'resource_form' => '4', 	'name' => 'description', 	'type' => 'textarea', 	'label' => 'Description', 												])
            ->create([	'resource_form' => '4', 	'name' => 'title', 	'type' => 'text', 	'label' => 'Group Title', 												])
            ->create([	'resource_form' => '5', 	'name' => 'name', 	'type' => 'text', 	'label' => 'Name', 												])
            ->create([	'resource_form' => '5', 	'name' => 'description', 	'type' => 'textarea', 	'label' => 'Description', 												])
            ->create([	'resource_form' => '5', 	'name' => 'title', 	'type' => 'text', 	'label' => 'Title', 												])
            ->create([	'resource_form' => '6', 	'name' => 'name', 	'type' => 'text', 	'label' => 'Name', 												])
            ->create([	'resource_form' => '6', 	'name' => 'description', 	'type' => 'textarea', 	'label' => 'Description', 												])
            ->create([	'resource_form' => '6', 	'name' => 'title', 	'type' => 'text', 	'label' => 'Title', 												])
            ->create([	'resource_form' => '6', 	'name' => 'namespace', 	'type' => 'text', 	'label' => 'Namespace', 												])
            ->create([	'resource_form' => '6', 	'name' => 'table', 	'type' => 'text', 	'label' => 'Table', 												])
            ->create([	'resource_form' => '6', 	'name' => 'key', 	'type' => 'text', 	'label' => 'Primary Key', 												])
            ->create([	'resource_form' => '6', 	'name' => 'controller', 	'type' => 'text', 	'label' => 'Controller Name', 												])
            ->create([	'resource_form' => '6', 	'name' => 'controller_namespace', 	'type' => 'text', 	'label' => 'Controller Namespace', 												])
            ->create([	'resource_form' => '7', 	'name' => 'name', 	'type' => 'text', 	'label' => 'Default Name', 												])
            ->create([	'resource_form' => '7', 	'name' => 'name_short', 	'type' => 'text', 	'label' => 'Short Name', 												])
            ->create([	'resource_form' => '7', 	'name' => 'name_long', 	'type' => 'text', 	'label' => 'Full Name', 												])
            ->create([	'resource_form' => '7', 	'name' => 'address_line1', 	'type' => 'textarea', 	'label' => 'Address Line 1', 												])
            ->create([	'resource_form' => '7', 	'name' => 'address_line2', 	'type' => 'textarea', 	'label' => 'Address Line 2', 												])
            ->create([	'resource_form' => '7', 	'name' => 'address_short', 	'type' => 'textarea', 	'label' => 'Short Address', 												])
            ->create([	'resource_form' => '7', 	'name' => 'address_long', 	'type' => 'textarea', 	'label' => 'Long Address', 												])
            ->create([	'resource_form' => '7', 	'name' => 'type', 	'type' => 'select', 	'label' => 'Contact Type', 	'collection' => 'Contacts', 											])
            ->create([	'resource_form' => '7', 	'name' => 'type_name', 	'type' => 'text', 	'label' => 'Type Name', 	'collection' => 'Contacts', 											])
            ->create([	'resource_form' => '7', 	'name' => 'detail', 	'type' => 'textarea', 	'label' => 'Detail', 	'collection' => 'Contacts', 											])
            ->create([	'resource_form' => '2', 	'name' => 'password', 	'type' => 'password', 	'label' => 'Password', 												])
            ->create([	'resource_form' => '3', 	'name' => 'password', 	'type' => 'password', 	'label' => 'Password', 												])
            ->create([	'resource_form' => '8', 	'name' => 'name', 	'type' => 'text', 	'label' => 'Name', 												])
            ->create([	'resource_form' => '8', 	'name' => 'email', 	'type' => 'text', 	'label' => 'Email', 												])
            ->create([	'resource_form' => '9', 	'name' => 'name', 	'type' => 'text', 	'label' => 'Name', 												])
            ->create([	'resource_form' => '9', 	'name' => 'email', 	'type' => 'text', 	'label' => 'Email', 												])
            ->create([	'resource_form' => '10', 	'name' => 'name', 	'type' => 'text', 	'label' => 'Name', 												])
            ->create([	'resource_form' => '10', 	'name' => 'description', 	'type' => 'textarea', 	'label' => 'Description', 												])
            ->create([	'resource_form' => '10', 	'name' => 'title', 	'type' => 'text', 	'label' => 'Title', 												])
            ->create([	'resource_form' => '10', 	'name' => 'namespace', 	'type' => 'text', 	'label' => 'Namespace', 												])
            ->create([	'resource_form' => '10', 	'name' => 'table', 	'type' => 'text', 	'label' => 'Table', 												])
            ->create([	'resource_form' => '10', 	'name' => 'controller', 	'type' => 'text', 	'label' => 'Controller', 												])
            ->create([	'resource_form' => '10', 	'name' => 'controller_namespace', 	'type' => 'text', 	'label' => 'Controller Namespace', 												])
            ->create([	'resource_form' => '11', 	'name' => 'resource', 	'type' => 'select', 	'label' => 'Resource', 												])
            ->create([	'resource_form' => '11', 	'name' => 'name', 	'type' => 'text', 	'label' => 'Name', 												])
            ->create([	'resource_form' => '11', 	'name' => 'description', 	'type' => 'textarea', 	'label' => 'Description', 												])
            ->create([	'resource_form' => '11', 	'name' => 'title', 	'type' => 'text', 	'label' => 'Title', 												])
            ->create([	'resource_form' => '11', 	'name' => 'icon_type', 	'type' => 'select', 	'label' => 'Icon Type', 												])
            ->create([	'resource_form' => '11', 	'name' => 'menu', 	'type' => 'text', 	'label' => 'Menu Title', 												])
            ->create([	'resource_form' => '11', 	'name' => 'icon', 	'type' => 'text', 	'label' => 'Icon', 												])
            ->create([	'resource_form' => '11', 	'name' => 'confirm', 	'type' => 'text', 	'label' => 'Confirmation Text', 												])
            ->create([	'resource_form' => '11', 	'name' => 'method_type', 	'type' => 'select', 	'label' => 'Method Type', 												])
            ->create([	'resource_form' => '11', 	'name' => 'idn1', 	'type' => 'select', 	'label' => 'Type ID 1', 												])
            ->create([	'resource_form' => '11', 	'name' => 'idn2', 	'type' => 'text', 	'label' => 'Type ID 2', 												])
            ->create([	'resource_form' => '12', 	'name' => 'resource', 	'type' => 'select', 	'label' => 'Resource', 												])
            ->create([	'resource_form' => '12', 	'name' => 'name', 	'type' => 'text', 	'label' => 'Name', 												])
            ->create([	'resource_form' => '12', 	'name' => 'description', 	'type' => 'textarea', 	'label' => 'Description', 												])
            ->create([	'resource_form' => '12', 	'name' => 'title', 	'type' => 'text', 	'label' => 'Title', 												])
            ->create([	'resource_form' => '12', 	'name' => 'action_text', 	'type' => 'text', 	'label' => 'Button Text', 												])
            ->create([	'resource_form' => '13', 	'name' => 'resource_form', 	'type' => 'select', 	'label' => 'Form', 												])
            ->create([	'resource_form' => '13', 	'name' => 'name', 	'type' => 'text', 	'label' => 'Name', 												])
            ->create([	'resource_form' => '13', 	'name' => 'type', 	'type' => 'text', 	'label' => 'Type', 												])
            ->create([	'resource_form' => '13', 	'name' => 'label', 	'type' => 'text', 	'label' => 'Label/Caption', 												])
            ->create([	'resource_form' => '13', 	'name' => 'relation', 	'type' => 'select', 	'label' => 'Relation', 												])
            ->create([	'resource_form' => '13', 	'name' => 'nest_relation1', 	'type' => 'select', 	'label' => 'Nest Relation 1', 												])
            ->create([	'resource_form' => '13', 	'name' => 'attribute', 	'type' => 'text', 	'label' => 'DB Field', 												])
            ->create([	'resource_form' => '14', 	'name' => 'form_field', 	'type' => 'select', 	'label' => 'Field', 												])
            ->create([	'resource_form' => '14', 	'name' => 'name', 	'type' => 'text', 	'label' => 'Attribute Name', 												])
            ->create([	'resource_form' => '14', 	'name' => 'value', 	'type' => 'text', 	'label' => 'Attribute Value', 												])
            ->create([	'resource_form' => '15', 	'name' => 'form_field', 	'type' => 'select', 	'label' => 'Field', 												])
            ->create([	'resource_form' => '15', 	'name' => 'type', 	'type' => 'select', 	'label' => 'Type', 												])
            ->create([	'resource_form' => '15', 	'name' => 'detail', 	'type' => 'text', 	'label' => 'List ID', 												])
            ->create([	'resource_form' => '15', 	'name' => 'value_attr', 	'type' => 'text', 	'label' => 'Value Attribute', 												])
            ->create([	'resource_form' => '15', 	'name' => 'label_attr', 	'type' => 'text', 	'label' => 'Label Attribute', 												])
            ->create([	'resource_form' => '15', 	'name' => 'preload', 	'type' => 'select', 	'label' => 'Preload', 												])
            ->create([	'resource_form' => '16', 	'name' => 'form_field', 	'type' => 'select', 	'label' => 'Field', 												])
            ->create([	'resource_form' => '16', 	'name' => 'rule', 	'type' => 'text', 	'label' => 'Rule', 												])
            ->create([	'resource_form' => '16', 	'name' => 'message', 	'type' => 'textarea', 	'label' => 'Message', 												])
            ->create([	'resource_form' => '16', 	'name' => 'arg1', 	'type' => 'text', 	'label' => 'Argument 1, If any', 												])
            ->create([	'resource_form' => '16', 	'name' => 'arg2', 	'type' => 'text', 	'label' => 'Argument 2, If any', 												])
            ->create([	'resource_form' => '16', 	'name' => 'arg3', 	'type' => 'text', 	'label' => 'Argument 3, If any', 												])
            ->create([	'resource_form' => '16', 	'name' => 'arg4', 	'type' => 'text', 	'label' => 'Argument 4, If any', 												])
            ->create([	'resource_form' => '16', 	'name' => 'arg5', 	'type' => 'text', 	'label' => 'Argument 5, If any', 												])
            ->create([	'resource_form' => '17', 	'name' => 'resource', 	'type' => 'select', 	'label' => 'Resource', 												])
            ->create([	'resource_form' => '17', 	'name' => 'name', 	'type' => 'text', 	'label' => 'Name', 												])
            ->create([	'resource_form' => '17', 	'name' => 'description', 	'type' => 'textarea', 	'label' => 'Description', 												])
            ->create([	'resource_form' => '17', 	'name' => 'title', 	'type' => 'text', 	'label' => 'Title', 												])
            ->create([	'resource_form' => '17', 	'name' => 'items_per_page', 	'type' => 'text', 	'label' => 'Items Per Page', 												])
            ->create([	'resource_form' => '17', 	'name' => 'resource_scope', 	'type' => 'select', 	'label' => 'Scopes', 												])
            ->create([	'resource_form' => '17', 	'name' => 'resource_action', 	'type' => 'select', 	'label' => 'Actions', 												])
            ->create([	'resource_form' => '18', 	'name' => 'resource', 	'type' => 'select', 	'label' => 'Resource', 												])
            ->create([	'resource_form' => '18', 	'name' => 'name', 	'type' => 'text', 	'label' => 'Name', 												])
            ->create([	'resource_form' => '18', 	'name' => 'description', 	'type' => 'textarea', 	'label' => 'Description', 												])
            ->create([	'resource_form' => '18', 	'name' => 'method', 	'type' => 'text', 	'label' => 'Method, if any', 												])
            ->create([	'resource_form' => '18', 	'name' => 'arg1', 	'type' => 'text', 	'label' => 'Argument 1, If any', 												])
            ->create([	'resource_form' => '18', 	'name' => 'arg2', 	'type' => 'text', 	'label' => 'Argument 2, If any', 												])
            ->create([	'resource_form' => '18', 	'name' => 'arg3', 	'type' => 'text', 	'label' => 'Argument 3, If any', 												])
            ->create([	'resource_form' => '19', 	'name' => 'resource', 	'type' => 'select', 	'label' => 'Resource', 												])
            ->create([	'resource_form' => '19', 	'name' => 'name', 	'type' => 'text', 	'label' => 'Name', 												])
            ->create([	'resource_form' => '19', 	'name' => 'description', 	'type' => 'textarea', 	'label' => 'Description', 												])
            ->create([	'resource_form' => '19', 	'name' => 'title_field', 	'type' => 'text', 	'label' => 'Title', 												])
            ->create([	'resource_form' => '19', 	'name' => 'resource_scope', 	'type' => 'select', 	'label' => 'Scopes', 												])
            ->create([	'resource_form' => '19', 	'name' => 'resource_action', 	'type' => 'select', 	'label' => 'Actions', 												])
            ->create([	'resource_form' => '20', 	'name' => 'resource_list', 	'type' => 'select', 	'label' => 'Resource List', 												])
            ->create([	'resource_form' => '20', 	'name' => 'label', 	'type' => 'text', 	'label' => 'Label', 												])
            ->create([	'resource_form' => '20', 	'name' => 'field', 	'type' => 'text', 	'label' => 'Field', 												])
            ->create([	'resource_form' => '20', 	'name' => 'relation', 	'type' => 'select', 	'label' => 'Relation, If any', 												])
            ->create([	'resource_form' => '20', 	'name' => 'nest_relation1', 	'type' => 'select', 	'label' => 'Nest Relation 1, if any', 												])
            ->create([	'resource_form' => '21', 	'name' => 'resource', 	'type' => 'select', 	'label' => 'Resource', 												])
            ->create([	'resource_form' => '21', 	'name' => 'relate_resource', 	'type' => 'select', 	'label' => 'Relate Resource', 												])
            ->create([	'resource_form' => '21', 	'name' => 'name', 	'type' => 'text', 	'label' => 'Name', 												])
            ->create([	'resource_form' => '21', 	'name' => 'description', 	'type' => 'textarea', 	'label' => 'Description', 												])
            ->create([	'resource_form' => '21', 	'name' => 'method', 	'type' => 'text', 	'label' => 'Method', 												])
            ->create([	'resource_form' => '21', 	'name' => 'type', 	'type' => 'select', 	'label' => 'Relation Type', 												])
            ->create([	'resource_form' => '22', 	'name' => 'resource_data', 	'type' => 'select', 	'label' => 'Resource Data', 												])
            ->create([	'resource_form' => '22', 	'name' => 'title', 	'type' => 'text', 	'label' => 'Title', 												])
            ->create([	'resource_form' => '22', 	'name' => 'title_field', 	'type' => 'text', 	'label' => 'Title Field', 												])
            ->create([	'resource_form' => '22', 	'name' => 'relation', 	'type' => 'select', 	'label' => 'Relation', 												])
            ->create([	'resource_form' => '22', 	'name' => 'colspan', 	'type' => 'text', 	'label' => 'Colspan/Bootstrap Size', 												])
            ->create([	'resource_form' => '23', 	'name' => 'section', 	'type' => 'select', 	'label' => 'Data Section', 												])
            ->create([	'resource_form' => '23', 	'name' => 'label', 	'type' => 'text', 	'label' => 'Label', 												])
            ->create([	'resource_form' => '23', 	'name' => 'attribute', 	'type' => 'text', 	'label' => 'Database Column', 												])
            ->create([	'resource_form' => '23', 	'name' => 'relation', 	'type' => 'select', 	'label' => 'Relation', 												])
            ->create([	'resource_form' => '24', 	'name' => 'resource_form', 	'type' => 'select', 	'label' => 'Primary Form', 												])
            ->create([	'resource_form' => '24', 	'name' => 'collection_form', 	'type' => 'select', 	'label' => 'Collection Form', 												])
            ->create([	'resource_form' => '24', 	'name' => 'relation', 	'type' => 'select', 	'label' => 'Relation', 												])
            ->create([	'resource_form' => '24', 	'name' => 'foreign_field', 	'type' => 'select', 	'label' => 'Foreign Field', 												])
            ->create([	'resource_form' => '25', 	'name' => 'resource_list', 	'type' => 'select', 	'label' => 'Resource List', 												])
            ->create([	'resource_form' => '25', 	'name' => 'field', 	'type' => 'text', 	'label' => 'DB Field', 												])
            ->create([	'resource_form' => '25', 	'name' => 'relation', 	'type' => 'select', 	'label' => 'Relation', 												])
            ->create([	'resource_form' => '25', 	'name' => 'nest_relation1', 	'type' => 'select', 	'label' => 'Nest Relation 1, if any', 												])
            ->create([	'resource_form' => '25', 	'name' => 'nest_relation2', 	'type' => 'select', 	'label' => 'Nest Relation 2, if any', 												])
            ->create([	'resource_form' => '26', 	'name' => 'form_field', 	'type' => 'select', 	'label' => 'Field', 												])
            ->create([	'resource_form' => '26', 	'name' => 'depend_field', 	'type' => 'text', 	'label' => 'Dependend Field', 												])
            ->create([	'resource_form' => '26', 	'name' => 'db_field', 	'type' => 'text', 	'label' => 'Database Column', 												])
            ->create([	'resource_form' => '26', 	'name' => 'operator', 	'type' => 'select', 	'label' => 'Compare Operator', 												])
            ->create([	'resource_form' => '26', 	'name' => 'compare_method', 	'type' => 'text', 	'label' => 'Compare Method', 												])
            ->create([	'resource_form' => '26', 	'name' => 'method', 	'type' => 'text', 	'label' => 'Method', 												])
            ->create([	'resource_form' => '26', 	'name' => 'value_db_field', 	'type' => 'text', 	'label' => 'Value Compare DB Field', 												])
            ->create([	'resource_form' => '26', 	'name' => 'ignore_null', 	'type' => 'select', 	'label' => 'Ignore if NULL', 												])
            ->create([	'resource_form' => '27', 	'name' => 'resource', 	'type' => 'select', 	'label' => 'Resource', 												])
            ->create([	'resource_form' => '27', 	'name' => 'name', 	'type' => 'text', 	'label' => 'Name', 												])
            ->create([	'resource_form' => '27', 	'name' => 'description', 	'type' => 'textarea', 	'label' => 'Description', 												])
            ->create([	'resource_form' => '27', 	'name' => 'title', 	'type' => 'text', 	'label' => 'Title', 												])
            ->create([	'resource_form' => '27', 	'name' => 'method', 	'type' => 'text', 	'label' => 'Method', 												])
            ->create([	'resource_form' => '28', 	'name' => 'resource_dashboard', 	'type' => 'select', 	'label' => 'Dashboard', 												])
            ->create([	'resource_form' => '28', 	'name' => 'name', 	'type' => 'text', 	'label' => 'Name', 												])
            ->create([	'resource_form' => '28', 	'name' => 'title', 	'type' => 'text', 	'label' => 'Title', 												])
            ->create([	'resource_form' => '28', 	'name' => 'height', 	'type' => 'text', 	'label' => 'Section Height in px', 												])
            ->create([	'resource_form' => '29', 	'name' => 'section', 	'type' => 'select', 	'label' => 'Dashboard Section', 												])
            ->create([	'resource_form' => '29', 	'name' => 'size', 	'type' => 'text', 	'label' => 'Size (Bootstrap col size)', 												])
            ->create([	'resource_form' => '29', 	'name' => 'title', 	'type' => 'text', 	'label' => 'Title', 												])
            ->create([	'resource_form' => '29', 	'name' => 'item', 	'type' => 'select', 	'label' => 'Item Type', 												])
            ->create([	'resource_form' => '29', 	'name' => 'item_id', 	'type' => 'text', 	'label' => 'Item ID', 												])
            ->create([	'resource_form' => '29', 	'name' => 'item_id2', 	'type' => 'text', 	'label' => 'Item ID 2', 												])
            ->create([	'resource_form' => '30', 	'name' => 'resource', 	'type' => 'select', 	'label' => 'Resource', 												])
            ->create([	'resource_form' => '30', 	'name' => 'name', 	'type' => 'text', 	'label' => 'Name', 												])
            ->create([	'resource_form' => '30', 	'name' => 'type', 	'type' => 'select', 	'label' => 'Metric Type', 												])
            ->create([	'resource_form' => '30', 	'name' => 'resource_list', 	'type' => 'select', 	'label' => 'Resource List', 												])
            ->create([	'resource_form' => '30', 	'name' => 'aggregate', 	'type' => 'select', 	'label' => 'Aggregate', 												])
            ->create([	'resource_form' => '30', 	'name' => 'aggregate_field', 	'type' => 'text', 	'label' => 'Aggregate Field', 												])
            ->create([	'resource_form' => '30', 	'name' => 'aggregate_distinct', 	'type' => 'select', 	'label' => 'Aggregate Distinct', 												])
            ->create([	'resource_form' => '30', 	'name' => 'field', 	'type' => 'text', 	'label' => 'Database Column', 												])
            ->create([	'resource_form' => '30', 	'name' => 'field_sub', 	'type' => 'text', 	'label' => 'Database Column 2', 												])
            ->create([	'resource_form' => '30', 	'name' => 'cache', 	'type' => 'text', 	'label' => 'Cache for Minutes', 												])
            ->create([	'resource_form' => '30', 	'name' => 'method', 	'type' => 'text', 	'label' => 'Method', 												])
            ->create([	'resource_form' => '31', 	'name' => 'form_field', 	'type' => 'select', 	'label' => 'Field', 												])
            ->create([	'resource_form' => '31', 	'name' => 'type', 	'type' => 'select', 	'label' => 'Alter type', 												])
            ->create([	'resource_form' => '31', 	'name' => 'depend_field', 	'type' => 'text', 	'label' => 'Depend on Field', 												])
            ->create([	'resource_form' => '31', 	'name' => 'alter_on', 	'type' => 'select', 	'label' => 'Alter Nature On', 												])
            ->create([	'resource_form' => '31', 	'name' => 'value', 	'type' => 'text', 	'label' => 'Value', 												])
            ->create([	'resource_form' => '31', 	'name' => 'values', 	'type' => 'text', 	'label' => 'Values', 												])
            ->create([	'resource_form' => '31', 	'name' => 'operator', 	'type' => 'select', 	'label' => 'Compare Operator', 												])
            ->create([	'resource_form' => '32', 	'name' => 'resource_list', 	'type' => 'select', 	'label' => 'Resource List', 												])
            ->create([	'resource_form' => '32', 	'name' => 'relation', 	'type' => 'select', 	'label' => 'Relation, If any', 												])
            ->create([	'resource_form' => '32', 	'name' => 'nest_relation1', 	'type' => 'select', 	'label' => 'Nest Relation 1, If any', 												])
            ->create([	'resource_form' => '32', 	'name' => 'nest_relation2', 	'type' => 'select', 	'label' => 'Nest Relation 2, If any', 												])
            ->create([	'resource_form' => '32', 	'name' => 'nest_relation3', 	'type' => 'select', 	'label' => 'Nest Relation 3, If any', 												])
            ->create([	'resource_form' => '32', 	'name' => 'nest_relation4', 	'type' => 'select', 	'label' => 'Nest Relation 4, If any', 												])
            ->create([	'resource_form' => '32', 	'name' => 'nest_relation5', 	'type' => 'select', 	'label' => 'Nest Relation 5, If any', 												])
            ->create([	'resource_form' => '33', 	'name' => 'resource_data', 	'type' => 'select', 	'label' => 'Resource Data', 												])
            ->create([	'resource_form' => '33', 	'name' => 'relation', 	'type' => 'select', 	'label' => 'Relation, If any', 												])
            ->create([	'resource_form' => '33', 	'name' => 'nest_relation1', 	'type' => 'select', 	'label' => 'Nest Relation 1, If any', 												])
            ->create([	'resource_form' => '33', 	'name' => 'nest_relation2', 	'type' => 'select', 	'label' => 'Nest Relation 2, If any', 												])
            ->create([	'resource_form' => '33', 	'name' => 'nest_relation3', 	'type' => 'select', 	'label' => 'Nest Relation 3, If any', 												])
            ->create([	'resource_form' => '33', 	'name' => 'nest_relation4', 	'type' => 'select', 	'label' => 'Nest Relation 4, If any', 												])
            ->create([	'resource_form' => '33', 	'name' => 'nest_relation5', 	'type' => 'select', 	'label' => 'Nest Relation 5, If any', 												])
        ;
        \DB::statement('set foreign_key_checks = ' . $_);
    }
}
