<?php

namespace Milestone\Appframe\Seeder;

use Illuminate\Database\Seeder;

class ResourceFormFieldTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $_ = \DB::statement('SELECT @@GLOBAL.foreign_key_checks');
        \DB::statement('set foreign_key_checks = 0');
        \Milestone\Appframe\Model\ResourceFormField::truncate()
            ->create([	'id' => '1', 	'resource_form' => '1', 	'name' => 'name', 	'type' => 'text', 	'label' => 'Name', 											])
            ->create([	'id' => '2', 	'resource_form' => '1', 	'name' => 'email', 	'type' => 'text', 	'label' => 'Email', 											])
            ->create([	'id' => '3', 	'resource_form' => '1', 	'name' => 'password', 	'type' => 'password', 	'label' => 'Password', 											])
            ->create([	'id' => '4', 	'resource_form' => '2', 	'name' => 'name', 	'type' => 'text', 	'label' => 'Name', 											])
            ->create([	'id' => '5', 	'resource_form' => '2', 	'name' => 'email', 	'type' => 'text', 	'label' => 'Email', 											])
            ->create([	'id' => '6', 	'resource_form' => '2', 	'name' => 'password', 	'type' => 'password', 	'label' => 'Password', 											])
            ->create([	'id' => '7', 	'resource_form' => '3', 	'name' => 'name', 	'type' => 'text', 	'label' => 'Name', 											])
            ->create([	'id' => '8', 	'resource_form' => '3', 	'name' => 'group', 	'type' => 'select', 	'label' => 'Group', 											])
            ->create([	'id' => '9', 	'resource_form' => '3', 	'name' => 'email', 	'type' => 'text', 	'label' => 'Email', 											])
            ->create([	'id' => '10', 	'resource_form' => '3', 	'name' => 'password', 	'type' => 'password', 	'label' => 'Password', 											])
            ->create([	'id' => '11', 	'resource_form' => '4', 	'name' => 'name', 	'type' => 'text', 	'label' => 'Name', 											])
            ->create([	'id' => '12', 	'resource_form' => '4', 	'name' => 'email', 	'type' => 'text', 	'label' => 'Email', 											])
            ->create([	'id' => '13', 	'resource_form' => '4', 	'name' => 'group', 	'type' => 'multiselect', 	'label' => 'Group', 											])
            ->create([	'id' => '14', 	'resource_form' => '5', 	'name' => 'password', 	'type' => 'password', 	'label' => 'Change Password to', 											])
            ->create([	'id' => '15', 	'resource_form' => '6', 	'name' => 'name', 	'type' => 'text', 	'label' => 'Name', 											])
            ->create([	'id' => '16', 	'resource_form' => '6', 	'name' => 'title', 	'type' => 'text', 	'label' => 'Title', 											])
            ->create([	'id' => '17', 	'resource_form' => '6', 	'name' => 'description', 	'type' => 'textarea', 	'label' => 'Description', 											])
            ->create([	'id' => '18', 	'resource_form' => '6', 	'name' => 'namespace', 	'type' => 'text', 	'label' => 'Namespace', 											])
            ->create([	'id' => '19', 	'resource_form' => '6', 	'name' => 'table', 	'type' => 'text', 	'label' => 'Table', 											])
            ->create([	'id' => '20', 	'resource_form' => '6', 	'name' => 'controller', 	'type' => 'text', 	'label' => 'Controller', 											])
            ->create([	'id' => '21', 	'resource_form' => '6', 	'name' => 'controller_namespace', 	'type' => 'text', 	'label' => 'Controller Namespace', 											])
            ->create([	'id' => '22', 	'resource_form' => '6', 	'name' => 'development', 	'type' => 'select', 	'label' => 'Development Resource', 											])
            ->create([	'id' => '23', 	'resource_form' => '7', 	'name' => 'resource', 	'type' => 'select', 	'label' => 'Select Resource', 											])
            ->create([	'id' => '24', 	'resource_form' => '7', 	'name' => 'name', 	'type' => 'text', 	'label' => 'Action Name', 											])
            ->create([	'id' => '25', 	'resource_form' => '7', 	'name' => 'menu', 	'type' => 'text', 	'label' => 'Main Menu Caption', 											])
            ->create([	'id' => '26', 	'resource_form' => '7', 	'name' => 'title', 	'type' => 'text', 	'label' => 'List Menu Caption', 											])
            ->create([	'id' => '27', 	'resource_form' => '7', 	'name' => 'description', 	'type' => 'textarea', 	'label' => 'Description', 											])
            ->create([	'id' => '28', 	'resource_form' => '7', 	'name' => 'type', 	'type' => 'select', 	'label' => 'Action Type', 											])
            ->create([	'id' => '29', 	'resource_form' => '7', 	'name' => 'idn1', 	'type' => 'select', 	'label' => 'Type Detail - 1', 											])
            ->create([	'id' => '30', 	'resource_form' => '7', 	'name' => 'idn2', 	'type' => 'select', 	'label' => 'Type Detail - 2', 											])
            ->create([	'id' => '31', 	'resource_form' => '7', 	'name' => 'idn3', 	'type' => 'select', 	'label' => 'Type Detail - 3', 											])
            ->create([	'id' => '32', 	'resource_form' => '8', 	'name' => 'resource', 	'type' => 'text', 	'label' => 'Select Resource', 											])
            ->create([	'id' => '33', 	'resource_form' => '8', 	'name' => 'name', 	'type' => 'text', 	'label' => 'Action Name', 											])
            ->create([	'id' => '34', 	'resource_form' => '8', 	'name' => 'menu', 	'type' => 'text', 	'label' => 'Main Menu Caption', 											])
            ->create([	'id' => '35', 	'resource_form' => '8', 	'name' => 'title', 	'type' => 'text', 	'label' => 'List Menu Caption', 											])
            ->create([	'id' => '36', 	'resource_form' => '8', 	'name' => 'description', 	'type' => 'textarea', 	'label' => 'Description', 											])
            ->create([	'id' => '37', 	'resource_form' => '8', 	'name' => 'type', 	'type' => 'select', 	'label' => 'Action Type', 											])
            ->create([	'id' => '38', 	'resource_form' => '8', 	'name' => 'idn1', 	'type' => 'select', 	'label' => 'Type Detail - 1', 											])
            ->create([	'id' => '39', 	'resource_form' => '8', 	'name' => 'idn2', 	'type' => 'select', 	'label' => 'Type Detail - 2', 											])
            ->create([	'id' => '40', 	'resource_form' => '8', 	'name' => 'idn3', 	'type' => 'select', 	'label' => 'Type Detail - 3', 											])
            ->create([	'id' => '41', 	'resource_form' => '9', 	'name' => 'resource', 	'type' => 'select', 	'label' => 'Select Resource', 											])
            ->create([	'id' => '42', 	'resource_form' => '9', 	'name' => 'name', 	'type' => 'text', 	'label' => 'Form Name', 											])
            ->create([	'id' => '43', 	'resource_form' => '9', 	'name' => 'title', 	'type' => 'text', 	'label' => 'Form Title', 											])
            ->create([	'id' => '44', 	'resource_form' => '9', 	'name' => 'action_text', 	'type' => 'text', 	'label' => 'Action Text', 											])
            ->create([	'id' => '45', 	'resource_form' => '9', 	'name' => 'description', 	'type' => 'textarea', 	'label' => 'Description', 											])
            ->create([	'id' => '46', 	'resource_form' => '10', 	'name' => 'resource', 	'type' => 'text', 	'label' => 'Select Resource', 											])
            ->create([	'id' => '47', 	'resource_form' => '10', 	'name' => 'name', 	'type' => 'text', 	'label' => 'Form Name', 											])
            ->create([	'id' => '48', 	'resource_form' => '10', 	'name' => 'title', 	'type' => 'text', 	'label' => 'Form Title', 											])
            ->create([	'id' => '49', 	'resource_form' => '10', 	'name' => 'action_text', 	'type' => 'text', 	'label' => 'Action Text', 											])
            ->create([	'id' => '50', 	'resource_form' => '10', 	'name' => 'description', 	'type' => 'textarea', 	'label' => 'Description', 											])
            ->create([	'id' => '51', 	'resource_form' => '11', 	'name' => 'resource_form', 	'type' => 'select', 	'label' => 'Select Form', 											])
            ->create([	'id' => '52', 	'resource_form' => '11', 	'name' => 'name', 	'type' => 'text', 	'label' => 'Name', 											])
            ->create([	'id' => '53', 	'resource_form' => '11', 	'name' => 'type', 	'type' => 'text', 	'label' => 'Type', 											])
            ->create([	'id' => '54', 	'resource_form' => '11', 	'name' => 'label', 	'type' => 'text', 	'label' => 'Label', 											])
            ->create([	'id' => '55', 	'resource_form' => '11', 	'name' => 'relation', 	'type' => 'select', 	'label' => 'Relation', 											])
            ->create([	'id' => '56', 	'resource_form' => '11', 	'name' => 'attribute', 	'type' => 'text', 	'label' => 'Attribute', 											])
            ->create([	'id' => '57', 	'resource_form' => '12', 	'name' => 'resource', 	'type' => 'select', 	'label' => 'Select Resource', 											])
            ->create([	'id' => '58', 	'resource_form' => '12', 	'name' => 'name', 	'type' => 'text', 	'label' => 'List Name', 											])
            ->create([	'id' => '59', 	'resource_form' => '12', 	'name' => 'title', 	'type' => 'text', 	'label' => 'Title', 											])
            ->create([	'id' => '60', 	'resource_form' => '12', 	'name' => 'identity', 	'type' => 'text', 	'label' => 'Field name to identify selected item', 											])
            ->create([	'id' => '61', 	'resource_form' => '12', 	'name' => 'items_per_page', 	'type' => 'text', 	'label' => 'Items to display per page', 											])
            ->create([	'id' => '62', 	'resource_form' => '12', 	'name' => 'description', 	'type' => 'textarea', 	'label' => 'Description', 											])
            ->create([	'id' => '63', 	'resource_form' => '13', 	'name' => 'resource', 	'type' => 'text', 	'label' => 'Resource', 											])
            ->create([	'id' => '64', 	'resource_form' => '13', 	'name' => 'name', 	'type' => 'text', 	'label' => 'List Name', 											])
            ->create([	'id' => '65', 	'resource_form' => '13', 	'name' => 'title', 	'type' => 'text', 	'label' => 'Title', 											])
            ->create([	'id' => '66', 	'resource_form' => '13', 	'name' => 'identity', 	'type' => 'text', 	'label' => 'Field name to identify selected item', 											])
            ->create([	'id' => '67', 	'resource_form' => '13', 	'name' => 'items_per_page', 	'type' => 'text', 	'label' => 'Items to display per page', 											])
            ->create([	'id' => '68', 	'resource_form' => '13', 	'name' => 'description', 	'type' => 'textarea', 	'label' => 'Description', 											])
            ->create([	'id' => '69', 	'resource_form' => '14', 	'name' => 'resource', 	'type' => 'select', 	'label' => 'Select Resource', 											])
            ->create([	'id' => '70', 	'resource_form' => '14', 	'name' => 'name', 	'type' => 'text', 	'label' => 'Name', 											])
            ->create([	'id' => '71', 	'resource_form' => '14', 	'name' => 'title_field', 	'type' => 'text', 	'label' => 'Title Field', 											])
            ->create([	'id' => '72', 	'resource_form' => '14', 	'name' => 'description', 	'type' => 'textarea', 	'label' => 'Description', 											])
            ->create([	'id' => '73', 	'resource_form' => '15', 	'name' => 'resource', 	'type' => 'text', 	'label' => 'Resource', 											])
            ->create([	'id' => '74', 	'resource_form' => '15', 	'name' => 'name', 	'type' => 'text', 	'label' => 'Name', 											])
            ->create([	'id' => '75', 	'resource_form' => '15', 	'name' => 'title_field', 	'type' => 'text', 	'label' => 'Title Field', 											])
            ->create([	'id' => '76', 	'resource_form' => '15', 	'name' => 'description', 	'type' => 'textarea', 	'label' => 'Description', 											])
            ->create([	'id' => '77', 	'resource_form' => '16', 	'name' => 'name', 	'type' => 'text', 	'label' => 'Name', 											])
            ->create([	'id' => '78', 	'resource_form' => '16', 	'name' => 'title', 	'type' => 'text', 	'label' => 'Title', 											])
            ->create([	'id' => '79', 	'resource_form' => '16', 	'name' => 'description', 	'type' => 'textarea', 	'label' => 'Description', 											])
            ->create([	'id' => '80', 	'resource_form' => '17', 	'name' => 'name', 	'type' => 'text', 	'label' => 'Name', 											])
            ->create([	'id' => '81', 	'resource_form' => '17', 	'name' => 'title', 	'type' => 'text', 	'label' => 'Title', 											])
            ->create([	'id' => '82', 	'resource_form' => '17', 	'name' => 'description', 	'type' => 'textarea', 	'label' => 'Description', 											])
            ->create([	'id' => '83', 	'resource_form' => '18', 	'name' => 'role', 	'type' => 'select', 	'label' => 'Select Role', 											])
            ->create([	'id' => '84', 	'resource_form' => '18', 	'name' => 'resource', 	'type' => 'select', 	'label' => 'Select Resource', 											])
            ->create([	'id' => '85', 	'resource_form' => '18', 	'name' => 'actions_availability', 	'type' => 'select', 	'label' => 'Actions Availability', 											])
            ->create([	'id' => '86', 	'resource_form' => '18', 	'name' => 'actions', 	'type' => 'multiselect', 	'label' => 'Select Actions', 											])
        ;
        \DB::statement('set foreign_key_checks = ' . $_);
    }
}
