<?php

namespace Milestone\Appframe\Seeder;

use Illuminate\Database\Seeder;

class ResourceFormFieldDataTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $_ = \DB::statement('SELECT @@GLOBAL.foreign_key_checks');
        \DB::statement('set foreign_key_checks = 0');
        \Milestone\Appframe\Model\ResourceFormFieldData::truncate()
            ->create([	'form_field' => '1', 	'attribute' => 'name', 														])
            ->create([	'form_field' => '2', 	'attribute' => 'email', 														])
            ->create([	'form_field' => '3', 		'relation' => '1', 													])
            ->create([	'form_field' => '4', 	'attribute' => 'name', 														])
            ->create([	'form_field' => '5', 	'attribute' => 'email', 														])
            ->create([	'form_field' => '6', 	'attribute' => 'name', 														])
            ->create([	'form_field' => '7', 	'attribute' => 'email', 														])
            ->create([	'form_field' => '8', 	'attribute' => 'name', 														])
            ->create([	'form_field' => '9', 	'attribute' => 'description', 														])
            ->create([	'form_field' => '10', 	'attribute' => 'title', 														])
            ->create([	'form_field' => '11', 	'attribute' => 'name', 														])
            ->create([	'form_field' => '12', 	'attribute' => 'description', 														])
            ->create([	'form_field' => '13', 	'attribute' => 'title', 														])
            ->create([	'form_field' => '14', 	'attribute' => 'name', 														])
            ->create([	'form_field' => '15', 	'attribute' => 'description', 														])
            ->create([	'form_field' => '16', 	'attribute' => 'title', 														])
            ->create([	'form_field' => '17', 	'attribute' => 'namespace', 														])
            ->create([	'form_field' => '18', 	'attribute' => 'table', 														])
            ->create([	'form_field' => '19', 	'attribute' => 'key', 														])
            ->create([	'form_field' => '20', 	'attribute' => 'controller', 														])
            ->create([	'form_field' => '21', 	'attribute' => 'controller_namespace', 														])
            ->create([	'form_field' => '22', 	'attribute' => 'name', 														])
            ->create([	'form_field' => '23', 	'attribute' => 'name_short', 														])
            ->create([	'form_field' => '24', 	'attribute' => 'name_long', 														])
            ->create([	'form_field' => '25', 	'attribute' => 'address_line1', 														])
            ->create([	'form_field' => '26', 	'attribute' => 'address_line2', 														])
            ->create([	'form_field' => '27', 	'attribute' => 'address_short', 														])
            ->create([	'form_field' => '28', 	'attribute' => 'address_long', 														])
            ->create([	'form_field' => '29', 	'attribute' => 'type', 	'relation' => '11', 													])
            ->create([	'form_field' => '30', 	'attribute' => 'type_name', 	'relation' => '11', 													])
            ->create([	'form_field' => '31', 	'attribute' => 'detail', 	'relation' => '11', 													])
            ->create([	'form_field' => '32', 	'attribute' => 'password', 														])
            ->create([	'form_field' => '33', 	'attribute' => 'password', 														])
            ->create([	'form_field' => '34', 	'attribute' => 'name', 														])
            ->create([	'form_field' => '35', 	'attribute' => 'email', 														])
            ->create([	'form_field' => '36', 	'attribute' => 'name', 														])
            ->create([	'form_field' => '37', 	'attribute' => 'email', 														])
            ->create([	'form_field' => '38', 	'attribute' => 'name', 														])
            ->create([	'form_field' => '39', 	'attribute' => 'description', 														])
            ->create([	'form_field' => '40', 	'attribute' => 'title', 														])
            ->create([	'form_field' => '41', 	'attribute' => 'namespace', 														])
            ->create([	'form_field' => '42', 	'attribute' => 'table', 														])
            ->create([	'form_field' => '43', 	'attribute' => 'controller', 														])
            ->create([	'form_field' => '44', 	'attribute' => 'controller_namespace', 														])
            ->create([	'form_field' => '45', 	'attribute' => 'resource', 														])
            ->create([	'form_field' => '46', 	'attribute' => 'name', 														])
            ->create([	'form_field' => '47', 	'attribute' => 'description', 														])
            ->create([	'form_field' => '48', 	'attribute' => 'title', 														])
            ->create([	'form_field' => '49', 	'attribute' => 'type', 														])
            ->create([	'form_field' => '50', 	'attribute' => 'menu', 														])
            ->create([	'form_field' => '51', 	'attribute' => 'icon', 														])
            ->create([	'form_field' => '52', 	'attribute' => 'confirm', 														])
            ->create([	'form_field' => '53', 	'attribute' => 'type', 	'relation' => '8', 													])
            ->create([	'form_field' => '54', 	'attribute' => 'idn1', 	'relation' => '8', 													])
            ->create([	'form_field' => '55', 	'attribute' => 'idn2', 	'relation' => '8', 													])
            ->create([	'form_field' => '56', 	'attribute' => 'resource', 														])
            ->create([	'form_field' => '57', 	'attribute' => 'name', 														])
            ->create([	'form_field' => '58', 	'attribute' => 'description', 														])
            ->create([	'form_field' => '59', 	'attribute' => 'title', 														])
            ->create([	'form_field' => '60', 	'attribute' => 'action_text', 														])
            ->create([	'form_field' => '61', 	'attribute' => 'resource_form', 														])
            ->create([	'form_field' => '62', 	'attribute' => 'name', 														])
            ->create([	'form_field' => '63', 	'attribute' => 'type', 														])
            ->create([	'form_field' => '64', 	'attribute' => 'label', 														])
            ->create([	'form_field' => '65', 	'attribute' => 'relation', 	'relation' => '20', 													])
            ->create([	'form_field' => '66', 	'attribute' => 'nest_relation1', 	'relation' => '20', 													])
            ->create([	'form_field' => '67', 	'attribute' => 'attribute', 	'relation' => '20', 													])
            ->create([	'form_field' => '68', 	'attribute' => 'form_field', 														])
            ->create([	'form_field' => '69', 	'attribute' => 'name', 														])
            ->create([	'form_field' => '70', 	'attribute' => 'value', 														])
            ->create([	'form_field' => '71', 	'attribute' => 'form_field', 														])
            ->create([	'form_field' => '72', 	'attribute' => 'type', 														])
            ->create([	'form_field' => '73', 	'attribute' => 'detail', 														])
            ->create([	'form_field' => '74', 	'attribute' => 'value_attr', 														])
            ->create([	'form_field' => '75', 	'attribute' => 'label_attr', 														])
            ->create([	'form_field' => '76', 	'attribute' => 'preload', 														])
            ->create([	'form_field' => '77', 	'attribute' => 'form_field', 														])
            ->create([	'form_field' => '78', 	'attribute' => 'rule', 														])
            ->create([	'form_field' => '79', 	'attribute' => 'message', 														])
            ->create([	'form_field' => '80', 	'attribute' => 'arg1', 														])
            ->create([	'form_field' => '81', 	'attribute' => 'arg2', 														])
            ->create([	'form_field' => '82', 	'attribute' => 'arg3', 														])
            ->create([	'form_field' => '83', 	'attribute' => 'arg4', 														])
            ->create([	'form_field' => '84', 	'attribute' => 'arg5', 														])
            ->create([	'form_field' => '85', 	'attribute' => 'resource', 														])
            ->create([	'form_field' => '86', 	'attribute' => 'name', 														])
            ->create([	'form_field' => '87', 	'attribute' => 'description', 														])
            ->create([	'form_field' => '88', 	'attribute' => 'title', 														])
            ->create([	'form_field' => '89', 	'attribute' => 'items_per_page', 														])
            ->create([	'form_field' => '90', 	'attribute' => 'resource_scope', 	'relation' => '27', 													])
            ->create([	'form_field' => '91', 	'attribute' => 'resource_action', 	'relation' => '52', 													])
            ->create([	'form_field' => '92', 	'attribute' => 'resource', 														])
            ->create([	'form_field' => '93', 	'attribute' => 'name', 														])
            ->create([	'form_field' => '94', 	'attribute' => 'description', 														])
            ->create([	'form_field' => '95', 	'attribute' => 'method', 														])
            ->create([	'form_field' => '96', 	'attribute' => 'arg1', 														])
            ->create([	'form_field' => '97', 	'attribute' => 'arg2', 														])
            ->create([	'form_field' => '98', 	'attribute' => 'arg3', 														])
            ->create([	'form_field' => '99', 	'attribute' => 'resource', 														])
            ->create([	'form_field' => '100', 	'attribute' => 'name', 														])
            ->create([	'form_field' => '101', 	'attribute' => 'description', 														])
            ->create([	'form_field' => '102', 	'attribute' => 'title_field', 														])
            ->create([	'form_field' => '103', 	'attribute' => 'resource_scope', 	'relation' => '51', 													])
            ->create([	'form_field' => '104', 	'attribute' => 'resource_action', 	'relation' => '53', 													])
            ->create([	'form_field' => '105', 	'attribute' => 'resource_list', 														])
            ->create([	'form_field' => '106', 	'attribute' => 'label', 														])
            ->create([	'form_field' => '107', 	'attribute' => 'field', 														])
            ->create([	'form_field' => '108', 	'attribute' => 'relation', 														])
            ->create([	'form_field' => '109', 	'attribute' => 'nest_relation1', 														])
            ->create([	'form_field' => '110', 	'attribute' => 'resource', 														])
            ->create([	'form_field' => '111', 	'attribute' => 'relate_resource', 														])
            ->create([	'form_field' => '112', 	'attribute' => 'name', 														])
            ->create([	'form_field' => '113', 	'attribute' => 'description', 														])
            ->create([	'form_field' => '114', 	'attribute' => 'method', 														])
            ->create([	'form_field' => '115', 	'attribute' => 'type', 														])
            ->create([	'form_field' => '116', 	'attribute' => 'resource_data', 														])
            ->create([	'form_field' => '117', 	'attribute' => 'title', 														])
            ->create([	'form_field' => '118', 	'attribute' => 'title_field', 														])
            ->create([	'form_field' => '119', 	'attribute' => 'relation', 														])
            ->create([	'form_field' => '120', 	'attribute' => 'colspan', 														])
            ->create([	'form_field' => '121', 	'attribute' => 'section', 														])
            ->create([	'form_field' => '122', 	'attribute' => 'label', 														])
            ->create([	'form_field' => '123', 	'attribute' => 'attribute', 														])
            ->create([	'form_field' => '124', 	'attribute' => 'relation', 														])
            ->create([	'form_field' => '125', 	'attribute' => 'resource_form', 														])
            ->create([	'form_field' => '126', 	'attribute' => 'collection_form', 														])
            ->create([	'form_field' => '127', 	'attribute' => 'relation', 														])
            ->create([	'form_field' => '128', 	'attribute' => 'foreign_field', 														])
            ->create([	'form_field' => '129', 	'attribute' => 'resource_list', 														])
            ->create([	'form_field' => '130', 	'attribute' => 'field', 														])
            ->create([	'form_field' => '131', 	'attribute' => 'relation', 														])
            ->create([	'form_field' => '132', 	'attribute' => 'nest_relation1', 														])
            ->create([	'form_field' => '133', 	'attribute' => 'nest_relation2', 														])
            ->create([	'form_field' => '134', 	'attribute' => 'form_field', 														])
            ->create([	'form_field' => '135', 	'attribute' => 'depend_field', 														])
            ->create([	'form_field' => '136', 	'attribute' => 'db_field', 														])
            ->create([	'form_field' => '137', 	'attribute' => 'operator', 														])
            ->create([	'form_field' => '138', 	'attribute' => 'compare_method', 														])
            ->create([	'form_field' => '139', 	'attribute' => 'method', 														])
            ->create([	'form_field' => '140', 	'attribute' => 'value_db_field', 														])
            ->create([	'form_field' => '141', 	'attribute' => 'ignore_null', 														])
            ->create([	'form_field' => '142', 	'attribute' => 'resource', 														])
            ->create([	'form_field' => '143', 	'attribute' => 'name', 														])
            ->create([	'form_field' => '144', 	'attribute' => 'description', 														])
            ->create([	'form_field' => '145', 	'attribute' => 'title', 														])
            ->create([	'form_field' => '146', 	'attribute' => 'method', 														])
            ->create([	'form_field' => '147', 	'attribute' => 'resource_dashboard', 														])
            ->create([	'form_field' => '148', 	'attribute' => 'name', 														])
            ->create([	'form_field' => '149', 	'attribute' => 'title', 														])
            ->create([	'form_field' => '150', 	'attribute' => 'height', 														])
            ->create([	'form_field' => '151', 	'attribute' => 'section', 														])
            ->create([	'form_field' => '152', 	'attribute' => 'size', 														])
            ->create([	'form_field' => '153', 	'attribute' => 'title', 														])
            ->create([	'form_field' => '154', 	'attribute' => 'item', 														])
            ->create([	'form_field' => '155', 	'attribute' => 'item_id', 														])
            ->create([	'form_field' => '156', 	'attribute' => 'item_id2', 														])
            ->create([	'form_field' => '157', 	'attribute' => 'resource', 														])
            ->create([	'form_field' => '158', 	'attribute' => 'name', 														])
            ->create([	'form_field' => '159', 	'attribute' => 'type', 														])
            ->create([	'form_field' => '160', 	'attribute' => 'resource_list', 														])
            ->create([	'form_field' => '161', 	'attribute' => 'aggregate', 														])
            ->create([	'form_field' => '162', 	'attribute' => 'aggregate_field', 														])
            ->create([	'form_field' => '163', 	'attribute' => 'aggregate_distinct', 														])
            ->create([	'form_field' => '164', 	'attribute' => 'field', 														])
            ->create([	'form_field' => '165', 	'attribute' => 'field_sub', 														])
            ->create([	'form_field' => '166', 	'attribute' => 'cache', 														])
            ->create([	'form_field' => '167', 	'attribute' => 'method', 														])
            ->create([	'form_field' => '168', 	'attribute' => 'form_field', 														])
            ->create([	'form_field' => '169', 	'attribute' => 'type', 														])
            ->create([	'form_field' => '170', 	'attribute' => 'depend_field', 														])
            ->create([	'form_field' => '171', 	'attribute' => 'alter_on', 														])
            ->create([	'form_field' => '172', 	'attribute' => 'value', 														])
            ->create([	'form_field' => '173', 	'attribute' => 'values', 														])
            ->create([	'form_field' => '174', 	'attribute' => 'operator', 														])
            ->create([	'form_field' => '175', 	'attribute' => 'resource_list', 														])
            ->create([	'form_field' => '176', 	'attribute' => 'relation', 														])
            ->create([	'form_field' => '177', 	'attribute' => 'nest_relation1', 														])
            ->create([	'form_field' => '178', 	'attribute' => 'nest_relation2', 														])
            ->create([	'form_field' => '179', 	'attribute' => 'nest_relation3', 														])
            ->create([	'form_field' => '180', 	'attribute' => 'nest_relation4', 														])
            ->create([	'form_field' => '181', 	'attribute' => 'nest_relation5', 														])
            ->create([	'form_field' => '182', 	'attribute' => 'resource_data', 														])
            ->create([	'form_field' => '183', 	'attribute' => 'relation', 														])
            ->create([	'form_field' => '184', 	'attribute' => 'nest_relation1', 														])
            ->create([	'form_field' => '185', 	'attribute' => 'nest_relation2', 														])
            ->create([	'form_field' => '186', 	'attribute' => 'nest_relation3', 														])
            ->create([	'form_field' => '187', 	'attribute' => 'nest_relation4', 														])
            ->create([	'form_field' => '188', 	'attribute' => 'nest_relation5', 														])
        ;
        \DB::statement('set foreign_key_checks = ' . $_);
    }
}
