<?php

namespace Milestone\Appframe\Seeder;

use Illuminate\Database\Seeder;

class ResourceFormFieldDataTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $_ = \DB::statement('SELECT @@GLOBAL.foreign_key_checks');
        \DB::statement('set foreign_key_checks = 0');
        \Milestone\Appframe\Model\ResourceFormFieldData::truncate()
            ->create([	'id' => '1', 	'form_field' => '1', 	'attribute' => 'name', 													])
            ->create([	'id' => '2', 	'form_field' => '2', 	'attribute' => 'email', 													])
            ->create([	'id' => '3', 	'form_field' => '3', 	'attribute' => 'password', 													])
            ->create([	'id' => '4', 	'form_field' => '4', 	'attribute' => 'name', 													])
            ->create([	'id' => '5', 	'form_field' => '5', 	'attribute' => 'email', 													])
            ->create([	'id' => '6', 	'form_field' => '6', 	'attribute' => 'password', 													])
            ->create([	'id' => '7', 	'form_field' => '7', 	'attribute' => 'name', 													])
            ->create([	'id' => '8', 	'form_field' => '8', 	'attribute' => 'group', 	'relation' => '1', 												])
            ->create([	'id' => '9', 	'form_field' => '9', 	'attribute' => 'email', 													])
            ->create([	'id' => '10', 	'form_field' => '10', 	'attribute' => 'password', 													])
            ->create([	'id' => '11', 	'form_field' => '11', 	'attribute' => 'name', 													])
            ->create([	'id' => '12', 	'form_field' => '12', 	'attribute' => 'email', 													])
            ->create([	'id' => '13', 	'form_field' => '13', 	'attribute' => 'group', 	'relation' => '1', 												])
            ->create([	'id' => '14', 	'form_field' => '14', 	'attribute' => 'password', 													])
            ->create([	'id' => '15', 	'form_field' => '15', 	'attribute' => 'name', 													])
            ->create([	'id' => '16', 	'form_field' => '16', 	'attribute' => 'title', 													])
            ->create([	'id' => '17', 	'form_field' => '17', 	'attribute' => 'description', 													])
            ->create([	'id' => '18', 	'form_field' => '18', 	'attribute' => 'namespace', 													])
            ->create([	'id' => '19', 	'form_field' => '19', 	'attribute' => 'table', 													])
            ->create([	'id' => '20', 	'form_field' => '20', 	'attribute' => 'controller', 													])
            ->create([	'id' => '21', 	'form_field' => '21', 	'attribute' => 'controller_namespace', 													])
            ->create([	'id' => '22', 	'form_field' => '22', 	'attribute' => 'development', 													])
            ->create([	'id' => '23', 	'form_field' => '23', 	'attribute' => 'resource', 													])
            ->create([	'id' => '24', 	'form_field' => '24', 	'attribute' => 'name', 													])
            ->create([	'id' => '25', 	'form_field' => '25', 	'attribute' => 'menu', 													])
            ->create([	'id' => '26', 	'form_field' => '26', 	'attribute' => 'title', 													])
            ->create([	'id' => '27', 	'form_field' => '27', 	'attribute' => 'description', 													])
            ->create([	'id' => '28', 	'form_field' => '28', 	'attribute' => 'type', 	'relation' => '8', 												])
            ->create([	'id' => '29', 	'form_field' => '29', 	'attribute' => 'idn1', 	'relation' => '8', 												])
            ->create([	'id' => '30', 	'form_field' => '30', 	'attribute' => 'idn2', 	'relation' => '8', 												])
            ->create([	'id' => '31', 	'form_field' => '31', 	'attribute' => 'idn3', 	'relation' => '8', 												])
            ->create([	'id' => '32', 	'form_field' => '32', 	'attribute' => 'resource', 													])
            ->create([	'id' => '33', 	'form_field' => '33', 	'attribute' => 'name', 													])
            ->create([	'id' => '34', 	'form_field' => '34', 	'attribute' => 'menu', 													])
            ->create([	'id' => '35', 	'form_field' => '35', 	'attribute' => 'title', 													])
            ->create([	'id' => '36', 	'form_field' => '36', 	'attribute' => 'description', 													])
            ->create([	'id' => '37', 	'form_field' => '37', 	'attribute' => 'type', 	'relation' => '8', 												])
            ->create([	'id' => '38', 	'form_field' => '38', 	'attribute' => 'idn1', 	'relation' => '8', 												])
            ->create([	'id' => '39', 	'form_field' => '39', 	'attribute' => 'idn2', 	'relation' => '8', 												])
            ->create([	'id' => '40', 	'form_field' => '40', 	'attribute' => 'idn3', 	'relation' => '8', 												])
            ->create([	'id' => '41', 	'form_field' => '41', 	'attribute' => 'resource', 													])
            ->create([	'id' => '42', 	'form_field' => '42', 	'attribute' => 'name', 													])
            ->create([	'id' => '43', 	'form_field' => '43', 	'attribute' => 'title', 													])
            ->create([	'id' => '44', 	'form_field' => '44', 	'attribute' => 'action_text', 													])
            ->create([	'id' => '45', 	'form_field' => '45', 	'attribute' => 'description', 													])
            ->create([	'id' => '46', 	'form_field' => '46', 	'attribute' => 'resource', 													])
            ->create([	'id' => '47', 	'form_field' => '47', 	'attribute' => 'name', 													])
            ->create([	'id' => '48', 	'form_field' => '48', 	'attribute' => 'title', 													])
            ->create([	'id' => '49', 	'form_field' => '49', 	'attribute' => 'action_text', 													])
            ->create([	'id' => '50', 	'form_field' => '50', 	'attribute' => 'description', 													])
            ->create([	'id' => '51', 	'form_field' => '51', 	'attribute' => 'resource_form', 													])
            ->create([	'id' => '52', 	'form_field' => '52', 	'attribute' => 'name', 													])
            ->create([	'id' => '53', 	'form_field' => '53', 	'attribute' => 'type', 													])
            ->create([	'id' => '54', 	'form_field' => '54', 	'attribute' => 'label', 													])
            ->create([	'id' => '55', 	'form_field' => '55', 	'attribute' => 'relation', 	'relation' => '21', 												])
            ->create([	'id' => '56', 	'form_field' => '56', 	'attribute' => 'attribute', 	'relation' => '21', 												])
            ->create([	'id' => '57', 	'form_field' => '57', 	'attribute' => 'resource', 													])
            ->create([	'id' => '58', 	'form_field' => '58', 	'attribute' => 'name', 													])
            ->create([	'id' => '59', 	'form_field' => '59', 	'attribute' => 'title', 													])
            ->create([	'id' => '60', 	'form_field' => '60', 	'attribute' => 'identity', 													])
            ->create([	'id' => '61', 	'form_field' => '61', 	'attribute' => 'items_per_page', 													])
            ->create([	'id' => '62', 	'form_field' => '62', 	'attribute' => 'description', 													])
            ->create([	'id' => '63', 	'form_field' => '63', 	'attribute' => 'resource', 													])
            ->create([	'id' => '64', 	'form_field' => '64', 	'attribute' => 'name', 													])
            ->create([	'id' => '65', 	'form_field' => '65', 	'attribute' => 'title', 													])
            ->create([	'id' => '66', 	'form_field' => '66', 	'attribute' => 'identity', 													])
            ->create([	'id' => '67', 	'form_field' => '67', 	'attribute' => 'items_per_page', 													])
            ->create([	'id' => '68', 	'form_field' => '68', 	'attribute' => 'description', 													])
            ->create([	'id' => '69', 	'form_field' => '69', 	'attribute' => 'resource', 													])
            ->create([	'id' => '70', 	'form_field' => '70', 	'attribute' => 'name', 													])
            ->create([	'id' => '71', 	'form_field' => '71', 	'attribute' => 'title_field', 													])
            ->create([	'id' => '72', 	'form_field' => '72', 	'attribute' => 'description', 													])
            ->create([	'id' => '73', 	'form_field' => '73', 	'attribute' => 'resource', 													])
            ->create([	'id' => '74', 	'form_field' => '74', 	'attribute' => 'name', 													])
            ->create([	'id' => '75', 	'form_field' => '75', 	'attribute' => 'title_field', 													])
            ->create([	'id' => '76', 	'form_field' => '76', 	'attribute' => 'description', 													])
            ->create([	'id' => '77', 	'form_field' => '77', 	'attribute' => 'name', 													])
            ->create([	'id' => '78', 	'form_field' => '78', 	'attribute' => 'title', 													])
            ->create([	'id' => '79', 	'form_field' => '79', 	'attribute' => 'description', 													])
            ->create([	'id' => '80', 	'form_field' => '80', 	'attribute' => 'name', 													])
            ->create([	'id' => '81', 	'form_field' => '81', 	'attribute' => 'title', 													])
            ->create([	'id' => '82', 	'form_field' => '82', 	'attribute' => 'description', 													])
            ->create([	'id' => '83', 	'form_field' => '83', 	'attribute' => 'role', 													])
            ->create([	'id' => '84', 	'form_field' => '84', 	'attribute' => 'resource', 													])
            ->create([	'id' => '85', 	'form_field' => '85', 	'attribute' => 'actions_availability', 													])
            ->create([	'id' => '86', 	'form_field' => '86', 	'attribute' => 'actions', 													])
        ;
        \DB::statement('set foreign_key_checks = ' . $_);
    }
}
